### ISSUE TITLE
Add prime video logo in Navbar

### ISSUE THREAD

**Issue by shivansh361** [shivansh361/prime-video-clone#1]

**Comment by kashish-d** [comment]
i can handle this

**Comment by Ashwani132003** [comment]
Hey I will add it, Do you want to add it in place of PRIME VIDEO in Top-left Nav Bar.
I can Do this, I had done these things.

**Comment by Hussain6** [comment]
Can I do this?

**Comment by himalaya0035** [comment]
Guys don't wait for anyone, just do it, if the maintainer likes your changes he would merge it.
Just do it
Make a pr
and wait for it to get merged
